name: Setup Nix

runs:
  using: "composite"
  steps:
    # - name: Install Nix
    #   uses: nixbuild/nix-quick-install-action@v26
    #
    # - name: Restore and cache Nix store
    #   uses: nix-community/cache-nix-action@v4
    #   with:
    #     key: cache-${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
    #     restore-keys: |
    #       cache-${{ runner.os }}-nix-store-
    - name: Install Nix
      uses: cachix/install-nix-action@v23

    - name: print PWD
      shell: bash -e {0}
      run: echo $PWD

    # - name: Create a custom shell for devenv
    #   shell: bash
    #   run: |
    #     mkdir -p $HOME/.local/bin
    #     echo "#!/usr/bin/env bash" > $HOME/.local/bin/devenv
    #     echo "nix develop --impure --command bash \"\$1\"" >> $HOME/.local/bin/devenv
    #     chmod +x $HOME/.local/bin/devenv

    # - name: print nix user conf
    #   shell: bash -e {0}
    #   run: cat $(echo $NIX_USER_CONF_FILES | sed "s/://g")

    - name: print pwd from nix develop shell
      shell: nix develop --impure --command bash -e {0}
      run: |
        echo 'PWD'
        echo $PWD
        echo 'nix eval getEnv'
        nix eval --impure --expr 'builtins.getEnv "PWD"'

    - name: Create a custom shell for devenv
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        echo "#!/usr/bin/env bash" > $HOME/.local/bin/custom-devenv
        echo "nix develop --impure --command bash \"\$1\"" >> $HOME/.local/bin/custom-devenv
        chmod +x $HOME/.local/bin/custom-devenv

    - name: custom devenv
      shell: custom-devenv {0}
      run: |
        echo 'PWD'
        echo $PWD
        echo 'nix eval getEnv'
        nix eval --impure --expr 'builtins.getEnv "PWD"'

    - name: print pwd from nix develop + devenv shell
      shell: nix develop .#devenv --impure --command bash -e {0}
      run: |
        echo 'PWD'
        echo $PWD
        echo 'nix eval getEnv'
        nix eval --impure --expr 'builtins.getEnv "PWD"'

    - name: Build the devenv shell
      shell: nix develop --impure --command bash -e {0}
      run: echo 🚀
